root = "."
tmp_dir = "tmp"

[build]
    args_bin = []
    bin = "./tmp/main.exe"
    cmd = "templ generate && go build -o ./tmp/main.exe ."
    post_cmd = ["echo build completed"]
    pre_cmd = ["echo starting build"]
    include_dir = []
    include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "js", "jpg", "jpeg", "svg"]
