root = "."
tmp_dir = "tmp"

[build]
    args_bin = []
    bin = "./tmp/server.exe"
    cmd = "go build -o ./tmp/server.exe ."
    post_cmd = ["echo build completed"]
    pre_cmd = ["echo starting build"]
    exclude_regex = [".*_templ.go"]
    exclude_unchanged = false
    follow_syslink = false
    full_bin=""
    delay = 1
    kill_delay = "0s"
    exclude_dir = ["assets", "tmp", "include_dir"]
    include_dir = []
    include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "js", "jpg", "jpeg", "svg"]

[proxy]
    enabled = true
    proxy_port = 3030
    app_port = 8080
